### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by zenspider** [RichardLitt/watch-gh-repos#32]
I've generated a new token, exported the env var, entered my username, password, and 2FA, now when I run I get:

```
944 % watch-gh-repos --org --unwatch chef
Unable to get GitHub repositories Error: Unwatching error
    at Promise.resolve.then.then.catch (/usr/local/lib/node_modules/watch-gh-repos/src/index.js:66:13)
    at tryCatcher (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)
undefined
```

**Comment by RichardLitt** [comment]
I wasn't able to replicate.

```
12:14 ~/src/watch-gh-repos (master) 🐕  watch-gh-repos --org --watch chef --token=$GITHUB_TOKEN
Watched: chef/.github
Watched: chef/anka-buildkite-plugin
Watched: chef/appbundle-updater
Watched: chef/appbundler
Watched: chef/artifactory-client
Watched: chef/automate
Watched: chef/automate-liveness-agent
Watched: chef/aws-s3
Watched: chef/bear
Watched: chef/bento
Watched: chef/bento-ya
Watched: chef/bft
Watched: chef/chef
Watched: chef/chef-apply
Watched: chef/chef-community-slack-meetings
Watched: chef/chef-core
Watched: chef/chef-dk
Watched: chef/chef-load
Watched: chef/chef-oss-practices
Watched: chef/chef-powershell-shim
Watched: chef/chef-provisioning
Watched: chef/chef-provisioning-aws
Watched: chef/chef-provisioning-fog
Watched: chef/chef-provisioning-ssh
Watched: chef/chef-push
Watched: chef/chef-ruby-lvm
Watched: chef/chef-ruby-lvm-attrib
Watched: chef/chef-server
Watched: chef/chef-server-data-generator
Watched: chef/chef-summit-2014
Watched: chef/chef-telemetry
Watched: chef/chef-triage-app
Watched: chef/chef-vault
Watched: chef/chef-vault-testfixtures
Watched: chef/chef-web-core
Watched: chef/chef-web-docs
Watched: chef/chef-windows-hardening
Watched: chef/chef-workstation
Watched: chef/chef-workstation-app
Watched: chef/chef-zero
Watched: chef/cheffish
Watched: chef/chefstyle
Watched: chef/chef_authn
Watched: chef/chef_backup
Watched: chef/chef_pgtap
Watched: chef/chef_reindex
Watched: chef/chef_req
Watched: chef/chef_secrets
Watched: chef/chocolatey-packages
Watched: chef/ci-studio-common
Watched: chef/community-summits
Watched: chef/community_cookbook_releaser
Watched: chef/community_engineering_cookbooks
Watched: chef/compliance-workshop-environment
Watched: chef/concrete
Watched: chef/config-mirror
Watched: chef/cookbook-omnifetch
Watched: chef/cookstyle
Watched: chef/covertool
Watched: chef/cowboy
Watched: chef/dafne-online-habitat
Watched: chef/dcob
Watched: chef/delivery-cli
Watched: chef/dep-selector
Watched: chef/dep-selector-libgecode
Watched: chef/devops-kungfu
Watched: chef/dmidecode_collection
Watched: chef/docker-buildkite-plugin
Watched: chef/efast_xs
Watched: chef/Emysql
Watched: chef/epgsql
Watched: chef/epgsql-1
Watched: chef/eredis
Watched: chef/erlang-bcrypt
Watched: chef/erlang-crypto2
Watched: chef/erlang-hmac-sha
Watched: chef/erlang_iso8601
Watched: chef/erlang_learning
Watched: chef/erlectricity
Watched: chef/erlsom
Watched: chef/erlware_commons
Watched: chef/erlzmq2
Watched: chef/esaml
Watched: chef/estatsd
Watched: chef/etap
Watched: chef/ethon
Watched: chef/fastmsi-custom-action
Watched: chef/ffi
Watched: chef/ffi-libarchive
Watched: chef/ffi-win32-extensions
Watched: chef/ffi-yajl
Watched: chef/fixie
Watched: chef/folsom
Watched: chef/folsom_graphite
Watched: chef/foulkon
Watched: chef/go-bindata
Watched: chef/gocovmerge
Watched: chef/habitat_exporter
Watched: chef/hoax
Watched: chef/homebrew-chef
Watched: chef/homebrew-chefops-tools
Watched: chef/homebrew-okta_aws
Watched: chef/ibrowse
Watched: chef/jazz_hands
Watched: chef/jiffy
Watched: chef/jump-in
Watched: chef/kitchen-vcenter
Watched: chef/knife-acl
Watched: chef/knife-azure
Watched: chef/knife-cloud
Watched: chef/knife-ec-backup
Watched: chef/knife-ec2
Watched: chef/knife-google
Watched: chef/knife-linode
Watched: chef/knife-lpar
Watched: chef/knife-opc
Watched: chef/knife-openstack
Watched: chef/knife-push
Watched: chef/knife-rackspace
Watched: chef/knife-tidy
Watched: chef/knife-vcenter
Watched: chef/knife-vsphere
Watched: chef/knife-windows
Watched: chef/lambda_ebs_snapshot
Watched: chef/libarchive-rust
Watched: chef/libarchive3-sys
Watched: chef/libyajl2-gem
Watched: chef/libzmq
Watched: chef/license-acceptance
Watched: chef/license_scout
Watched: chef/load-grunt-config
Watched: chef/marketo_chef
Watched: chef/mini_s3
Watched: chef/mixer
Watched: chef/mixlib-archive
Watched: chef/mixlib-authentication
Watched: chef/mixlib-cli
Watched: chef/mixlib-config
Watched: chef/mixlib-install
Watched: chef/mixlib-log
Watched: chef/mixlib-shellout
Watched: chef/mixlib-versioning
Watched: chef/mlsa
Watched: chef/moser
Watched: chef/national-parks
Watched: chef/net-scp-chef
Watched: chef/oauth-ng
Watched: chef/ohai
Watched: chef/okta_aws
Watched: chef/omniauth-chef
Watched: chef/omniauth-chef-oauth2
Watched: chef/omnibus
Watched: chef/omnibus-ctl
Watched: chef/omnibus-harmony
Watched: chef/omnibus-software
Watched: chef/omnibus-toolchain
Watched: chef/omnitruck
Watched: chef/opscode-darklaunch-erlang
Watched: chef/opscode-pushy-client
Watched: chef/opscode-pushy-server
Watched: chef/opscode-pushy-simulator
Watched: chef/opscode-summit-2013
Watched: chef/opscoderl_folsom
Watched: chef/opscoderl_httpc
Watched: chef/opscoderl_wm
Watched: chef/oss_project_boilerplate
Watched: chef/os_release
Watched: chef/proxy_tests
Watched: chef/pushy_common
Watched: chef/push_jobs_test_infra
Watched: chef/qa-chef-server-cluster
Watched: chef/rabbit_common
Watched: chef/rbzmq
Watched: chef/rebar
Watched: chef/relx
Watched: chef/rs-chef-api
Watched: chef/ruby-unf_ext
Watched: chef/s3-tests
Watched: chef/sample-aha-integration
Watched: chef/scaffolding-chef
Watched: chef/scaffolding-go
Watched: chef/scaffolding-inspec
Watched: chef/slackin
Watched: chef/sqerl
Watched: chef/stats_hero
Watched: chef/supermarket
Watched: chef/toml
Watched: chef/vault-dynamodb
Watched: chef/webmachine
Watched: chef/welcome_bot
Watched: chef/win32-certstore
Watched: chef/win32-dir
Watched: chef/win32-event
Watched: chef/win32-eventlog
Watched: chef/win32-file
Watched: chef/win32-ipc
Watched: chef/win32-mmap
Watched: chef/win32-mutex
Watched: chef/win32-process
Watched: chef/win32-security
Watched: chef/win32-service
Watched: chef/win32-taskscheduler
Watched: chef/wmi-lite
12:15 ~/src/watch-gh-repos (master) 🐕  watch-gh-repos --org --unwatch chef --token=$GITHUB_TOKEN
Unwatched: chef/.github
Unwatched: chef/anka-buildkite-plugin
Unwatched: chef/appbundle-updater
Unwatched: chef/appbundler
Unwatched: chef/artifactory-client
Unwatched: chef/automate
Unwatched: chef/automate-liveness-agent
Unwatched: chef/aws-s3
Unwatched: chef/bear
Unwatched: chef/bento
Unwatched: chef/bento-ya
Unwatched: chef/bft
Unwatched: chef/chef
Unwatched: chef/chef-apply
Unwatched: chef/chef-community-slack-meetings
Unwatched: chef/chef-core
Unwatched: chef/chef-dk
Unwatched: chef/chef-load
Unwatched: chef/chef-oss-practices
Unwatched: chef/chef-powershell-shim
Unwatched: chef/chef-provisioning
Unwatched: chef/chef-provisioning-aws
Unwatched: chef/chef-provisioning-fog
Unwatched: chef/chef-provisioning-ssh
Unwatched: chef/chef-push
Unwatched: chef/chef-ruby-lvm
Unwatched: chef/chef-ruby-lvm-attrib
Unwatched: chef/chef-server
Unwatched: chef/chef-server-data-generator
Unwatched: chef/chef-summit-2014
Unwatched: chef/chef-telemetry
Unwatched: chef/chef-triage-app
Unwatched: chef/chef-vault
Unwatched: chef/chef-vault-testfixtures
Unwatched: chef/chef-web-core
Unwatched: chef/chef-web-docs
Unwatched: chef/chef-windows-hardening
Unwatched: chef/chef-workstation
Unwatched: chef/chef-workstation-app
Unwatched: chef/chef-zero
Unwatched: chef/cheffish
Unwatched: chef/chefstyle
Unwatched: chef/chef_authn
Unwatched: chef/chef_backup
Unwatched: chef/chef_pgtap
Unwatched: chef/chef_reindex
Unwatched: chef/chef_req
Unwatched: chef/chef_secrets
Unwatched: chef/chocolatey-packages
Unwatched: chef/ci-studio-common
Unwatched: chef/community-summits
Unwatched: chef/community_cookbook_releaser
Unwatched: chef/community_engineering_cookbooks
Unwatched: chef/compliance-workshop-environment
Unwatched: chef/concrete
Unwatched: chef/config-mirror
Unwatched: chef/cookbook-omnifetch
Unwatched: chef/cookstyle
Unwatched: chef/covertool
Unwatched: chef/cowboy
Unwatched: chef/dafne-online-habitat
Unwatched: chef/dcob
Unwatched: chef/delivery-cli
Unwatched: chef/dep-selector
Unwatched: chef/dep-selector-libgecode
Unwatched: chef/devops-kungfu
Unwatched: chef/dmidecode_collection
Unwatched: chef/docker-buildkite-plugin
Unwatched: chef/efast_xs
Unwatched: chef/Emysql
Unwatched: chef/epgsql
Unwatched: chef/epgsql-1
Unwatched: chef/eredis
Unwatched: chef/erlang-bcrypt
Unwatched: chef/erlang-crypto2
Unwatched: chef/erlang-hmac-sha
Unwatched: chef/erlang_iso8601
Unwatched: chef/erlang_learning
Unwatched: chef/erlectricity
Unwatched: chef/erlsom
Unwatched: chef/erlware_commons
Unwatched: chef/erlzmq2
Unwatched: chef/esaml
Unwatched: chef/estatsd
Unwatched: chef/etap
Unwatched: chef/ethon
Unwatched: chef/fastmsi-custom-action
Unwatched: chef/ffi
Unwatched: chef/ffi-libarchive
Unwatched: chef/ffi-win32-extensions
Unwatched: chef/ffi-yajl
Unwatched: chef/fixie
Unwatched: chef/folsom
Unwatched: chef/folsom_graphite
Unwatched: chef/foulkon
Unwatched: chef/go-bindata
Unwatched: chef/gocovmerge
Unwatched: chef/habitat_exporter
Unwatched: chef/hoax
Unwatched: chef/homebrew-chef
Unwatched: chef/homebrew-chefops-tools
Unwatched: chef/homebrew-okta_aws
Unwatched: chef/ibrowse
Unwatched: chef/jazz_hands
Unwatched: chef/jiffy
Unwatched: chef/jump-in
Unwatched: chef/kitchen-vcenter
Unwatched: chef/knife-acl
Unwatched: chef/knife-azure
Unwatched: chef/knife-cloud
Unwatched: chef/knife-ec-backup
Unwatched: chef/knife-ec2
Unwatched: chef/knife-google
Unwatched: chef/knife-linode
Unwatched: chef/knife-lpar
Unwatched: chef/knife-opc
Unwatched: chef/knife-openstack
Unwatched: chef/knife-push
Unwatched: chef/knife-rackspace
Unwatched: chef/knife-tidy
Unwatched: chef/knife-vcenter
Unwatched: chef/knife-vsphere
Unwatched: chef/knife-windows
Unwatched: chef/lambda_ebs_snapshot
Unwatched: chef/libarchive-rust
Unwatched: chef/libarchive3-sys
Unwatched: chef/libyajl2-gem
Unwatched: chef/libzmq
Unwatched: chef/license-acceptance
Unwatched: chef/license_scout
Unwatched: chef/load-grunt-config
Unwatched: chef/marketo_chef
Unwatched: chef/mini_s3
Unwatched: chef/mixer
Unwatched: chef/mixlib-archive
Unwatched: chef/mixlib-authentication
Unwatched: chef/mixlib-cli
Unwatched: chef/mixlib-config
Unwatched: chef/mixlib-install
Unwatched: chef/mixlib-log
Unwatched: chef/mixlib-shellout
Unwatched: chef/mixlib-versioning
Unwatched: chef/mlsa
Unwatched: chef/moser
Unwatched: chef/national-parks
Unwatched: chef/net-scp-chef
Unwatched: chef/oauth-ng
Unwatched: chef/ohai
Unwatched: chef/okta_aws
Unwatched: chef/omniauth-chef
Unwatched: chef/omniauth-chef-oauth2
Unwatched: chef/omnibus
Unwatched: chef/omnibus-ctl
Unwatched: chef/omnibus-harmony
Unwatched: chef/omnibus-software
Unwatched: chef/omnibus-toolchain
Unwatched: chef/omnitruck
Unwatched: chef/opscode-darklaunch-erlang
Unwatched: chef/opscode-pushy-client
Unwatched: chef/opscode-pushy-server
Unwatched: chef/opscode-pushy-simulator
Unwatched: chef/opscode-summit-2013
Unwatched: chef/opscoderl_folsom
Unwatched: chef/opscoderl_httpc
Unwatched: chef/opscoderl_wm
Unwatched: chef/oss_project_boilerplate
Unwatched: chef/os_release
Unwatched: chef/proxy_tests
Unwatched: chef/pushy_common
Unwatched: chef/push_jobs_test_infra
Unwatched: chef/qa-chef-server-cluster
Unwatched: chef/rabbit_common
Unwatched: chef/rbzmq
Unwatched: chef/rebar
Unwatched: chef/relx
Unwatched: chef/rs-chef-api
Unwatched: chef/ruby-unf_ext
Unwatched: chef/s3-tests
Unwatched: chef/sample-aha-integration
Unwatched: chef/scaffolding-chef
Unwatched: chef/scaffolding-go
Unwatched: chef/scaffolding-inspec
Unwatched: chef/slackin
Unwatched: chef/sqerl
Unwatched: chef/stats_hero
Unwatched: chef/supermarket
Unwatched: chef/toml
Unwatched: chef/vault-dynamodb
Unwatched: chef/webmachine
Unwatched: chef/welcome_bot
Unwatched: chef/win32-certstore
Unwatched: chef/win32-dir
Unwatched: chef/win32-event
Unwatched: chef/win32-eventlog
Unwatched: chef/win32-file
Unwatched: chef/win32-ipc
Unwatched: chef/win32-mmap
Unwatched: chef/win32-mutex
Unwatched: chef/win32-process
Unwatched: chef/win32-security
Unwatched: chef/win32-service
Unwatched: chef/win32-taskscheduler
Unwatched: chef/wmi-lite
```

**Comment by RichardLitt** [comment]
Let me know if this doesn't work if you provide the token with the right scopes directly!

**Comment by zenspider** [comment]
I'm not sure why you closed this. I provided a clear reproduction, using your usage instructions, that you said you couldn't reproduce, yet you show that you're running the command with your workaround, not the same way as I did.

Not sure what to say to that. 🤷‍♀

**Comment by RichardLitt** [comment]
I closed it because I solved it to my satisfaction, and I was pretty sure it would work for me. How were you providing the token? That isn't a workaround, it's one of the ways it can be sent. 

People approach open source differently, mate.

**Comment by zenspider** [comment]
As I said in the issue description:

> exported the env var

**Comment by RichardLitt** [comment]
Can you try running `$ GITHUB_TOKEN=<token> watch-gh-repos --org --watch chef`?

**Comment by RichardLitt** [comment]
@zenspider Ping.

**Comment by zenspider** [comment]
Given that there is literally no semantic difference between exporting the variable and providing it on the command... I'm guessing it is still a problem. But I've moved on.

**Comment by RichardLitt** [comment]
@zenspider Word. Might be the same issue as #43. Thanks for your help.
