### ISSUE TITLE
ghauth?

### ISSUE THREAD

**Issue by zeke** [RichardLitt/watch-gh-repos#8]
Hey @RichardLitt long time no see cool repo. :)

Would you be open to a PR that adds [ghauth](http://ghub.io/ghauth) to the CLI?

**Comment by RichardLitt** [comment]
100% open. Do it!

**Comment by RichardLitt** [comment]
Note that this works, too: https://github.com/RichardLitt/watch-gh-repos/blob/master/src/index.js#L9

**Comment by RichardLitt** [comment]
@zeke Any chance you'd be interested in doing this sooner, rather than later? I'm finding I need this now. Otherwise, I can do it. :)

**Comment by zeke** [comment]
I'm so busy right now! If you can do it, that would be awesome. 💛

**Comment by RichardLitt** [comment]
@zeke Done. :)

**Comment by zeke** [comment]
👏

**Comment by zeke** [comment]
I got an error:

```
$ which watch
watch: aliased to watch-gh-repos

$ watch ayojs/ayo
Your GitHub username: zeke
Your GitHub password: ✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔

Your GitHub OTP/2FA Code (optional): XXXXXX
Error: Unable to get repo statisticsError: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
    at Promise.resolve.then.catch (/usr/local/lib/node_modules/watch-gh-repos/src/index.js:36:13)
    at tryCatcher (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/watch-gh-repos/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by RichardLitt** [comment]
This has been fixed.

**Comment by zeke** [comment]
Works for me now. Thanks, @RichardLitt 🙏
